# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/ssynthesia/ghostcity/git-collab/gkisalatiga/simon-petrus/qtdesigner-ui/dialog_persembahan.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(633, 286)
        self.button_box = QtWidgets.QDialogButtonBox(Dialog)
        self.button_box.setGeometry(QtCore.QRect(20, 240, 591, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.app_title = QtWidgets.QLabel(Dialog)
        self.app_title.setGeometry(QtCore.QRect(10, 10, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.app_title.setFont(font)
        self.app_title.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.app_title.setObjectName("app_title")
        self.app_title_2 = QtWidgets.QLabel(Dialog)
        self.app_title_2.setGeometry(QtCore.QRect(10, 30, 491, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.app_title_2.setFont(font)
        self.app_title_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.app_title_2.setObjectName("app_title_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 100, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 160, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.field_bank_abbr = QtWidgets.QLineEdit(Dialog)
        self.field_bank_abbr.setGeometry(QtCore.QRect(180, 70, 431, 24))
        self.field_bank_abbr.setObjectName("field_bank_abbr")
        self.field_bank_name = QtWidgets.QLineEdit(Dialog)
        self.field_bank_name.setGeometry(QtCore.QRect(180, 100, 431, 24))
        self.field_bank_name.setObjectName("field_bank_name")
        self.field_number = QtWidgets.QLineEdit(Dialog)
        self.field_number.setGeometry(QtCore.QRect(180, 130, 431, 24))
        self.field_number.setObjectName("field_number")
        self.field_holder = QtWidgets.QLineEdit(Dialog)
        self.field_holder.setGeometry(QtCore.QRect(180, 160, 431, 24))
        self.field_holder.setObjectName("field_holder")
        self.label_status = QtWidgets.QLabel(Dialog)
        self.label_status.setGeometry(QtCore.QRect(180, 190, 431, 21))
        self.label_status.setObjectName("label_status")

        self.retranslateUi(Dialog)
        self.button_box.accepted.connect(Dialog.accept) # type: ignore
        self.button_box.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.app_title.setText(_translate("Dialog", "[Placeholder Title]"))
        self.app_title_2.setText(_translate("Dialog", "Masukkan informasi terkait rekening bank yang akan ditampilkan kepada jemaat."))
        self.label_5.setText(_translate("Dialog", "Singkatan Bank"))
        self.label_6.setText(_translate("Dialog", "Nama Lengkap Bank"))
        self.label_7.setText(_translate("Dialog", "Nomor Rekening"))
        self.label_8.setText(_translate("Dialog", "Pemilik Rekening"))
        self.field_bank_abbr.setPlaceholderText(_translate("Dialog", "BCA, CIMB, MANDIRI, dsb."))
        self.field_bank_name.setPlaceholderText(_translate("Dialog", "Bank Central Asia, dsb."))
        self.field_number.setPlaceholderText(_translate("Dialog", "Angka ditulis tanpa spasi maupun titik"))
        self.field_holder.setPlaceholderText(_translate("Dialog", "Nama pemilik rekening bank (misal, GKI Salatiga)"))
        self.label_status.setText(_translate("Dialog", "-"))
