# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/ssynthesia/ghostcity/git-collab/gkisalatiga/simon-petrus/qtdesigner-ui/dialog_playlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(633, 534)
        self.button_box = QtWidgets.QDialogButtonBox(Dialog)
        self.button_box.setGeometry(QtCore.QRect(20, 490, 591, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.app_title = QtWidgets.QLabel(Dialog)
        self.app_title.setGeometry(QtCore.QRect(10, 10, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.app_title.setFont(font)
        self.app_title.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.app_title.setObjectName("app_title")
        self.app_title_2 = QtWidgets.QLabel(Dialog)
        self.app_title_2.setGeometry(QtCore.QRect(10, 30, 601, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.app_title_2.setFont(font)
        self.app_title_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.app_title_2.setObjectName("app_title_2")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(20, 80, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.playlist_type = QtWidgets.QComboBox(Dialog)
        self.playlist_type.setGeometry(QtCore.QRect(180, 80, 291, 24))
        self.playlist_type.setObjectName("playlist_type")
        self.playlist_type.addItem("")
        self.playlist_type.addItem("")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 110, 601, 371))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.fragment_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.fragment_layout.setContentsMargins(0, 0, 0, 0)
        self.fragment_layout.setObjectName("fragment_layout")

        self.retranslateUi(Dialog)
        self.button_box.accepted.connect(Dialog.accept) # type: ignore
        self.button_box.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tambah/Edit Daftar Putar YouTube"))
        self.app_title.setText(_translate("Dialog", "[Placeholder Title]"))
        self.app_title_2.setText(_translate("Dialog", "Masukkan informasi terkait poster komedi putar yang akan dipublikasikan."))
        self.label_11.setText(_translate("Dialog", "Jenis Daftar Putar"))
        self.playlist_type.setItemText(0, _translate("Dialog", "Playlist Reguler"))
        self.playlist_type.setItemText(1, _translate("Dialog", "RSS"))
