# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/ssynthesia/ghostcity/git-collab/gkisalatiga/simon-petrus/qtdesigner-ui/dialog_gallery.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(584, 421)
        self.button_box = QtWidgets.QDialogButtonBox(Dialog)
        self.button_box.setGeometry(QtCore.QRect(10, 380, 561, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.app_title = QtWidgets.QLabel(Dialog)
        self.app_title.setGeometry(QtCore.QRect(10, 10, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.app_title.setFont(font)
        self.app_title.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.app_title.setObjectName("app_title")
        self.app_title_2 = QtWidgets.QLabel(Dialog)
        self.app_title_2.setGeometry(QtCore.QRect(10, 30, 491, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.app_title_2.setFont(font)
        self.app_title_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.app_title_2.setObjectName("app_title_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 80, 161, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 161, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.field_title = QtWidgets.QLineEdit(Dialog)
        self.field_title.setGeometry(QtCore.QRect(192, 80, 381, 21))
        self.field_title.setObjectName("field_title")
        self.field_url = QtWidgets.QLineEdit(Dialog)
        self.field_url.setGeometry(QtCore.QRect(192, 110, 381, 21))
        self.field_url.setObjectName("field_url")
        self.label_status = QtWidgets.QLabel(Dialog)
        self.label_status.setGeometry(QtCore.QRect(190, 350, 381, 16))
        self.label_status.setObjectName("label_status")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 161, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.field_story = QtWidgets.QPlainTextEdit(Dialog)
        self.field_story.setGeometry(QtCore.QRect(190, 140, 381, 201))
        self.field_story.setObjectName("field_story")

        self.retranslateUi(Dialog)
        self.button_box.accepted.connect(Dialog.accept) # type: ignore
        self.button_box.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tambah/Edit Formulir"))
        self.app_title.setText(_translate("Dialog", "[Placeholder Title]"))
        self.app_title_2.setText(_translate("Dialog", "Masukkan data terkait folder album yang akan ditambahkan."))
        self.label.setText(_translate("Dialog", "Judul Folder"))
        self.label_2.setText(_translate("Dialog", "Tautan Google Drive"))
        self.field_title.setPlaceholderText(_translate("Dialog", "Dokumentasi Sekolah Alkitab Liburan, dsb."))
        self.field_url.setPlaceholderText(_translate("Dialog", "https://drive.google.com/drive/folders/..."))
        self.label_status.setText(_translate("Dialog", "-"))
        self.label_3.setText(_translate("Dialog", "Kisah"))
