# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/ssynthesia/ghostcity/git-collab/gkisalatiga/simon-petrus/qtdesigner-ui/frame_playlist_rss.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrameRSS(object):
    def setupUi(self, FrameRSS):
        FrameRSS.setObjectName("FrameRSS")
        FrameRSS.resize(583, 102)
        self.label_5 = QtWidgets.QLabel(FrameRSS)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.field_title = QtWidgets.QLineEdit(FrameRSS)
        self.field_title.setGeometry(QtCore.QRect(170, 10, 401, 24))
        self.field_title.setObjectName("field_title")
        self.field_key = QtWidgets.QLineEdit(FrameRSS)
        self.field_key.setGeometry(QtCore.QRect(170, 40, 401, 24))
        self.field_key.setObjectName("field_key")
        self.label_8 = QtWidgets.QLabel(FrameRSS)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_status = QtWidgets.QLabel(FrameRSS)
        self.label_status.setGeometry(QtCore.QRect(170, 70, 351, 21))
        self.label_status.setObjectName("label_status")

        self.retranslateUi(FrameRSS)
        QtCore.QMetaObject.connectSlotsByName(FrameRSS)

    def retranslateUi(self, FrameRSS):
        _translate = QtCore.QCoreApplication.translate
        FrameRSS.setWindowTitle(_translate("FrameRSS", "Frame"))
        self.label_5.setText(_translate("FrameRSS", "Judul"))
        self.field_title.setPlaceholderText(_translate("FrameRSS", "Kumpulan Video SaRen, dsb."))
        self.field_key.setPlaceholderText(_translate("FrameRSS", "SaRen, dsb."))
        self.label_8.setText(_translate("FrameRSS", "Kata Kunci"))
        self.label_status.setText(_translate("FrameRSS", "-"))
