# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/ssynthesia/ghostcity/git-collab/gkisalatiga/simon-petrus/qtdesigner-ui/frame_playlist_regular.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrameRegular(object):
    def setupUi(self, FrameRegular):
        FrameRegular.setObjectName("FrameRegular")
        FrameRegular.resize(583, 102)
        self.label_5 = QtWidgets.QLabel(FrameRegular)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.field_title = QtWidgets.QLineEdit(FrameRegular)
        self.field_title.setGeometry(QtCore.QRect(170, 10, 401, 24))
        self.field_title.setObjectName("field_title")
        self.field_url = QtWidgets.QLineEdit(FrameRegular)
        self.field_url.setGeometry(QtCore.QRect(170, 40, 401, 24))
        self.field_url.setObjectName("field_url")
        self.label_8 = QtWidgets.QLabel(FrameRegular)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_status = QtWidgets.QLabel(FrameRegular)
        self.label_status.setGeometry(QtCore.QRect(170, 70, 351, 21))
        self.label_status.setObjectName("label_status")

        self.retranslateUi(FrameRegular)
        QtCore.QMetaObject.connectSlotsByName(FrameRegular)

    def retranslateUi(self, FrameRegular):
        _translate = QtCore.QCoreApplication.translate
        FrameRegular.setWindowTitle(_translate("FrameRegular", "Frame"))
        self.label_5.setText(_translate("FrameRegular", "Judul"))
        self.field_title.setPlaceholderText(_translate("FrameRegular", "Kumpulan Video Pentakosta, dsb."))
        self.field_url.setPlaceholderText(_translate("FrameRegular", "https://www.youtube.com/playlist?list=..."))
        self.label_8.setText(_translate("FrameRegular", "URL Playlist YouTube"))
        self.label_status.setText(_translate("FrameRegular", "-"))
