# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/ssynthesia/ghostcity/git-collab/gkisalatiga/simon-petrus/qtdesigner-ui/frame_formulir.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(580, 376)
        self.btn_save = QtWidgets.QPushButton(Frame)
        self.btn_save.setGeometry(QtCore.QRect(30, 320, 101, 31))
        self.btn_save.setObjectName("btn_save")
        self.app_title = QtWidgets.QLabel(Frame)
        self.app_title.setGeometry(QtCore.QRect(20, 10, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.app_title.setFont(font)
        self.app_title.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.app_title.setObjectName("app_title")
        self.btn_add = QtWidgets.QPushButton(Frame)
        self.btn_add.setGeometry(QtCore.QRect(510, 70, 31, 31))
        self.btn_add.setObjectName("btn_add")
        self.btn_move_up = QtWidgets.QPushButton(Frame)
        self.btn_move_up.setGeometry(QtCore.QRect(510, 110, 31, 31))
        self.btn_move_up.setObjectName("btn_move_up")
        self.btn_move_down = QtWidgets.QPushButton(Frame)
        self.btn_move_down.setGeometry(QtCore.QRect(510, 150, 31, 31))
        self.btn_move_down.setObjectName("btn_move_down")
        self.btn_edit = QtWidgets.QPushButton(Frame)
        self.btn_edit.setGeometry(QtCore.QRect(510, 190, 31, 31))
        self.btn_edit.setObjectName("btn_edit")
        self.btn_delete = QtWidgets.QPushButton(Frame)
        self.btn_delete.setGeometry(QtCore.QRect(510, 230, 31, 31))
        self.btn_delete.setObjectName("btn_delete")
        self.list_forms = QtWidgets.QListWidget(Frame)
        self.list_forms.setGeometry(QtCore.QRect(30, 70, 471, 241))
        self.list_forms.setObjectName("list_forms")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.btn_save.setText(_translate("Frame", "✅    SIMPAN"))
        self.app_title.setText(_translate("Frame", "Formulir GKI Salatiga"))
        self.btn_add.setToolTip(_translate("Frame", "Tambah formulir baru"))
        self.btn_add.setText(_translate("Frame", "➕"))
        self.btn_move_up.setToolTip(_translate("Frame", "Pindah posisi formulir ke atas"))
        self.btn_move_up.setText(_translate("Frame", "⏫"))
        self.btn_move_down.setToolTip(_translate("Frame", "Pindah posisi formulir ke bawah"))
        self.btn_move_down.setText(_translate("Frame", "⏬"))
        self.btn_edit.setToolTip(_translate("Frame", "Ubah formulir terpilih"))
        self.btn_edit.setText(_translate("Frame", "🖉"))
        self.btn_delete.setToolTip(_translate("Frame", "Hapus formulir"))
        self.btn_delete.setText(_translate("Frame", "🗑"))
