# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/ssynthesia/ghostcity/git-collab/gkisalatiga/simon-petrus/qtdesigner-ui/frame_carousel_article.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrameArticle(object):
    def setupUi(self, FrameArticle):
        FrameArticle.setObjectName("FrameArticle")
        FrameArticle.resize(583, 362)
        self.label_5 = QtWidgets.QLabel(FrameArticle)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.field_title = QtWidgets.QLineEdit(FrameArticle)
        self.field_title.setGeometry(QtCore.QRect(170, 10, 401, 24))
        self.field_title.setObjectName("field_title")
        self.field_url = QtWidgets.QLineEdit(FrameArticle)
        self.field_url.setGeometry(QtCore.QRect(170, 70, 401, 24))
        self.field_url.setObjectName("field_url")
        self.field_date = QtWidgets.QLabel(FrameArticle)
        self.field_date.setGeometry(QtCore.QRect(170, 40, 341, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.field_date.setFont(font)
        self.field_date.setObjectName("field_date")
        self.label_6 = QtWidgets.QLabel(FrameArticle)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(FrameArticle)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_status = QtWidgets.QLabel(FrameArticle)
        self.label_status.setGeometry(QtCore.QRect(170, 140, 351, 21))
        self.label_status.setObjectName("label_status")
        self.label_11 = QtWidgets.QLabel(FrameArticle)
        self.label_11.setGeometry(QtCore.QRect(10, 100, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.btn_img_select = QtWidgets.QPushButton(FrameArticle)
        self.btn_img_select.setEnabled(True)
        self.btn_img_select.setGeometry(QtCore.QRect(170, 100, 61, 24))
        self.btn_img_select.setObjectName("btn_img_select")
        self.txt_img_loc = QtWidgets.QLabel(FrameArticle)
        self.txt_img_loc.setEnabled(True)
        self.txt_img_loc.setGeometry(QtCore.QRect(310, 100, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.txt_img_loc.setFont(font)
        self.txt_img_loc.setObjectName("txt_img_loc")
        self.btn_img_view = QtWidgets.QPushButton(FrameArticle)
        self.btn_img_view.setEnabled(True)
        self.btn_img_view.setGeometry(QtCore.QRect(240, 100, 61, 24))
        self.btn_img_view.setObjectName("btn_img_view")

        self.retranslateUi(FrameArticle)
        QtCore.QMetaObject.connectSlotsByName(FrameArticle)

    def retranslateUi(self, FrameArticle):
        _translate = QtCore.QCoreApplication.translate
        FrameArticle.setWindowTitle(_translate("FrameArticle", "Frame"))
        self.label_5.setText(_translate("FrameArticle", "Judul"))
        self.field_title.setPlaceholderText(_translate("FrameArticle", "Artikel Sapaan Gembala GKI Salatiga, dsb."))
        self.field_url.setPlaceholderText(_translate("FrameArticle", "https://www.gkisalatiga.org, dsb."))
        self.field_date.setText(_translate("FrameArticle", "[Placeholder Text]"))
        self.label_6.setText(_translate("FrameArticle", "Tanggal Pembuatan"))
        self.label_8.setText(_translate("FrameArticle", "URL Artikel"))
        self.label_status.setText(_translate("FrameArticle", "-"))
        self.label_11.setText(_translate("FrameArticle", "Thumbnail"))
        self.btn_img_select.setText(_translate("FrameArticle", "Pilih ..."))
        self.txt_img_loc.setText(_translate("FrameArticle", "Tidak ada berkas terpilih."))
        self.btn_img_view.setText(_translate("FrameArticle", "Lihat ..."))
