# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/ssynthesia/ghostcity/git-collab/gkisalatiga/simon-petrus/qtdesigner-ui/frame_liturgi_upload.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(580, 563)
        self.btn_upload = QtWidgets.QPushButton(Frame)
        self.btn_upload.setGeometry(QtCore.QRect(170, 490, 101, 31))
        self.btn_upload.setObjectName("btn_upload")
        self.app_title = QtWidgets.QLabel(Frame)
        self.app_title.setGeometry(QtCore.QRect(20, 10, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.app_title.setFont(font)
        self.app_title.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.app_title.setObjectName("app_title")
        self.btn_pdf_select = QtWidgets.QPushButton(Frame)
        self.btn_pdf_select.setGeometry(QtCore.QRect(170, 200, 111, 24))
        self.btn_pdf_select.setObjectName("btn_pdf_select")
        self.txt_pdf_loc = QtWidgets.QLabel(Frame)
        self.txt_pdf_loc.setGeometry(QtCore.QRect(290, 200, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.txt_pdf_loc.setFont(font)
        self.txt_pdf_loc.setObjectName("txt_pdf_loc")
        self.label_6 = QtWidgets.QLabel(Frame)
        self.label_6.setGeometry(QtCore.QRect(20, 200, 141, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Frame)
        self.label_7.setGeometry(QtCore.QRect(20, 270, 141, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.txt_cred_loc_2 = QtWidgets.QLabel(Frame)
        self.txt_cred_loc_2.setGeometry(QtCore.QRect(20, 60, 551, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.txt_cred_loc_2.setFont(font)
        self.txt_cred_loc_2.setObjectName("txt_cred_loc_2")
        self.label_status = QtWidgets.QLabel(Frame)
        self.label_status.setGeometry(QtCore.QRect(280, 490, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.checkBox = QtWidgets.QCheckBox(Frame)
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QtCore.QRect(170, 230, 341, 31))
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.label_8 = QtWidgets.QLabel(Frame)
        self.label_8.setGeometry(QtCore.QRect(20, 230, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.date_picker = QtWidgets.QCalendarWidget(Frame)
        self.date_picker.setGeometry(QtCore.QRect(170, 270, 321, 211))
        self.date_picker.setObjectName("date_picker")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.btn_upload.setText(_translate("Frame", "🚀    UNGGAH"))
        self.app_title.setText(_translate("Frame", "Unggah Tata Ibadah"))
        self.btn_pdf_select.setText(_translate("Frame", "Pilih Berkas ..."))
        self.txt_pdf_loc.setText(_translate("Frame", "Tidak ada berkas terpilih."))
        self.label_6.setText(_translate("Frame", "PDF Tata Ibadah"))
        self.label_7.setText(_translate("Frame", "Tanggal Ibadah"))
        self.txt_cred_loc_2.setText(_translate("Frame", "Unggah PDF tata ibadah tanpa ribet!\n"
"\n"
"Fitur ini akan secara otomatis melakukan hal berikut untuk Anda:\n"
"- Mengunggah PDF tata ibadah ke folder terpadu Google Drive GKI Salatiga\n"
"- Mempos tata ibadah terbaru pada situs web GKISalatiga.org\n"
"- Mendeteksi thumbnail PDF tata ibadah dan menampilkannya di pos situs web\n"
""))
        self.label_status.setText(_translate("Frame", "-"))
        self.checkBox.setText(_translate("Frame", "Deteksi otomatis gambar pratinjau PDF"))
        self.label_8.setText(_translate("Frame", "Thumbnail Pos"))
